### ISSUE TITLE
Create a "Brand Toolkit" to help with standardizing CSS

### ISSUE THREAD

**Issue by jessicajiang** [purdue-epics-isd/TRACK#12]
Elements to Include: 
- [x] Heading 1
- [x] Heading 2
- [x] Paragraph
- [x] General body structure (background, colors, etc.)
- [ ] General buttons
- [x] Submit buttons
- [x] Back buttons
- [x] Profile Picture/Profile buttons
- [ ] Drop down menus
- [ ] Grids
- [x] Nav bar

**Comment by ashleyKing9** [comment]
Also, @conley-tjahjono try to use the class names that I've already created in main.css because I reference those within the html pages already, and it will make things soo much easier
