### ISSUE TITLE
Class Page (OG)

### ISSUE THREAD

**Issue by jessicajiang** [purdue-epics-isd/TRACK#5]
- [x] Add drop-down to teacher view and ability to show different classes
- [x] Reach goals:
   - [x] Ability to create grid from an array of students rather than a hard-coded list
   - [x] Ability to go to actual student profiles with goals generated from database
- [x] Include log out button
- [x] Include add new student button
- [x] Center header
- [x] Make it clearer that the drop-down for different classes is a dropdown and not just static (ex. add an down arrow visual?)

**Comment by shwethaumashanker** [comment]
Add new student button
