### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by ashleyKing9** [purdue-epics-isd/TRACK#9]
- [x] Make all goal boxes the same width
- [x] Add graphs (evaluation history) for:
- - [x] Single data point
- - [x] Single rubric
- [x] Include information entered from “Create New Student” page
- [x] Add IEP Detail Section at the bottom of the page
- [ ] Add total evaluations and last evaluation tab in existing goal page

**Comment by coryvitez** [comment]
couldn't figure out how to do part one.
